--- #YAML:1.0
name:               PDF-GetImages
version:            1.18
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              1.03
    File::Copy:        2.08
    File::Find::Rule:  0.30
    File::Path:        2.04
    File::Spec:        3.17
    File::Which:       0.05
    Test::Simple:      0.8
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
