# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-GetImages
version:      1.13
version_from: lib/PDF/GetImages.pm
installdirs:  site
requires:
    Carp:                          1.03
    File::Copy:                    2.08
    File::Find::Rule:              0.30
    File::Path:                    2.04
    File::Spec:                    3.17
    File::Which:                   0.05
    Test::Simple:                  0.8

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
